### PR TITLE
fix for folder names without version

### PR DESCRIPTION
**Pull request by suisseWalter**
potential fix for #99 

it works in my space exploration file. but there might be other mods where it might crash.

### CODE REVIEW

**Comment by saulrh** [comment]
It looks like this might only work when _all_ mods leave the version off - 

```
Traceback (most recent call last):
  File "auto.py", line 880, in <module>
    auto(*sys.argv[1:])
  File "auto.py", line 804, in auto
    zipInfo = zipObj.getinfo(os.path.join(mod[0], icon + ".png").replace('\\', '/'))
  File "/usr/lib/python3.8/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'krastorio2/graphics/icons/fluids/oil.png' in the archive"
saul@enki ~/D/f/f/m/L0laapk3_FactorioMaps ((a63a1594…)) [1]> zipinfo -l ../../mods/Krastorio2_1.1.4.zip | grep oil.png
-rw-r--r--  4.5 unx    12174 bl    12179 defN 21-May-19 05:26 Krastorio2_1.1.4/graphics/icons/entities/tesla-coil.png
-rw-r--r--  4.5 unx     5794 bl     5799 defN 21-May-19 05:26 Krastorio2_1.1.4/graphics/icons/fluids/heavy-oil.png
-rw-r--r--  4.5 unx     6021 bl     6026 defN 21-May-19 05:26 Krastorio2_1.1.4/graphics/icons/fluids/light-oil.png
-rw-r--r--  4.5 unx     5117 bl     5122 defN 21-May-19 05:26 Krastorio2_1.1.4/graphics/icons/fluids/oil.png
-rw-r--r--  4.5 unx     2831 bl     2836 defN 21-May-19 05:26 Krastorio2_1.1.4/graphics/icons/resources/crude-oil.png
-rw-r--r--  4.5 unx    47598 bl    47546 defN 21-May-19 05:26 Krastorio2_1.1.4/graphics/resources/crude-oil.png
-rw-r--r--  4.5 unx    43888 bl    43903 defN 21-May-19 05:26 Krastorio2_1.1.4/graphics/technologies/matter-oil.png
-rw-r--r--  4.5 unx    36922 bl    36937 defN 21-May-19 05:26 Krastorio2_1.1.4/graphics/technologies/tesla-coil.png
```

**Comment by L0laapk3** [comment]
Apparently this PR crashes for mods that *do* have a version in the folder name. The problem should probably be addressed at https://github.com/L0laapk3/FactorioMaps/blob/master/auto.py#L742 rather than trying to fix the symptoms.
I'll try to have a look at it over the next days or if someone else wants to do it, feel free :p

**Comment by L0laapk3** [comment]
The `--no-tags` flag can be used as a workaround until this is addressed.

**Comment by L0laapk3** [comment]
Closing in favor of #101 .

**Pull request closed without merging**
